apiVersion: v1
kind: PersistentVolume
metadata:
  serviceAccount: argo-workflows-workflows 
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-05-03T17:02:27Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: ci-pv
  resourceVersion: "469216"
  uid: c8c98bf5-8062-4dfb-93b2-7c5a356c9137
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ci-example-sqjf7-workdir
    namespace: default
    resourceVersion: "462498"
    uid: 7937dbbe-5a67-4f0c-9100-b7df741cad19
  local:
    path: /mnt/ci
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: local-pv
          operator: In
          values:
          - "1"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Released
